blueprint:
  name: ASHRAE 55 Adaptive Climate Control
  description: >
    Intelligent climate control implementing ASHRAE 55 adaptive comfort model with energy optimization.
    
    This blueprint dynamically adjusts comfort zones based on outdoor temperature, provides 15-30% energy savings,
    and works seamlessly with SmartIR and other climate platforms.
    
  domain: automation
  author: Marco Sinhoreli
  source_url: https://github.com/msinhore/adaptive-climate-blueprint
  
  input:
    climate_entity:
      name: Climate Entity
      description: The climate device to control (SmartIR, generic thermostat, etc.)
      selector:
        entity:
          domain: climate
    
    indoor_temp_sensor:
      name: Indoor Temperature Sensor
      description: Temperature sensor for the room being controlled
      selector:
        entity:
          domain: sensor
          device_class: temperature
    
    outdoor_temp_sensor:
      name: Outdoor Temperature Sensor
      description: External temperature sensor or weather service for adaptive comfort calculations
      selector:
        entity:
          domain: 
            - sensor
            - weather
    
    occupancy_sensor:
      name: Occupancy Sensor (Optional)
      description: Motion or presence sensor for occupancy-aware control
      default: ""
      selector:
        entity:
          domain: binary_sensor
          device_class: 
            - motion
            - occupancy
            - presence
    
    comfort_category:
      name: ASHRAE 55 Comfort Category
      description: >
        Comfort category based on ASHRAE 55 standard:
        - Category I: ±2°C (90% satisfaction) - Office environments
        - Category II: ±3°C (80% satisfaction) - Typical residential 
        - Category III: ±4°C (65% satisfaction) - Maximum energy savings
      default: "II"
      selector:
        select:
          options:
            - label: "Category I (±2°C - 90% satisfaction)"
              value: "I"
            - label: "Category II (±3°C - 80% satisfaction)"
              value: "II"
            - label: "Category III (±4°C - 65% satisfaction)"
              value: "III"
    
    energy_save_mode:
      name: Energy Save Mode
      description: Enable enhanced energy saving features
      default: true
      selector:
        boolean:
    
    natural_ventilation_enable:
      name: Natural Ventilation Detection
      description: Automatically turn off HVAC when natural ventilation is sufficient
      default: true
      selector:
        boolean:
    
    natural_ventilation_threshold:
      name: Natural Ventilation Threshold
      description: Temperature difference threshold for natural ventilation (°C)
      default: 2.0
      selector:
        number:
          min: 0.5
          max: 5.0
          step: 0.5
          unit_of_measurement: "°C"
    
    setback_temperature_offset:
      name: Setback Temperature Offset
      description: Temperature offset when room is unoccupied (°C)
      default: 2.0
      selector:
        number:
          min: 1.0
          max: 5.0
          step: 0.5
          unit_of_measurement: "°C"
    
    min_comfort_temp:
      name: Minimum Comfort Temperature
      description: Absolute minimum comfort temperature (°C)
      default: 18.0
      selector:
        number:
          min: 15.0
          max: 22.0
          step: 0.5
          unit_of_measurement: "°C"
    
    max_comfort_temp:
      name: Maximum Comfort Temperature
      description: Absolute maximum comfort temperature (°C)
      default: 28.0
      selector:
        number:
          min: 25.0
          max: 32.0
          step: 0.5
          unit_of_measurement: "°C"
    
    # Advanced Comfort Parameters (Optional)
    mean_radiant_temp_sensor:
      name: Mean Radiant Temperature Sensor (Optional)
      description: Sensor for mean radiant temperature measurement (near windows, heated surfaces)
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: temperature
    
    indoor_humidity_sensor:
      name: Indoor Humidity Sensor (Optional)
      description: Relative humidity sensor for enhanced comfort calculation
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: humidity
    
    outdoor_humidity_sensor:
      name: Outdoor Humidity Sensor (Optional)
      description: Outdoor humidity sensor or weather service for natural ventilation decisions
      default: ""
      selector:
        entity:
          domain: 
            - sensor
            - weather
    
    use_operative_temperature:
      name: Use Operative Temperature
      description: Enable operative temperature calculation (requires radiant temperature sensor)
      default: false
      selector:
        boolean:
    
    air_velocity:
      name: Air Velocity (m/s)
      description: Typical air velocity in the space (affects cooling sensation)
      default: 0.1
      selector:
        number:
          min: 0.0
          max: 2.0
          step: 0.1
          unit_of_measurement: "m/s"
    
    adaptive_air_velocity:
      name: Adaptive Air Velocity Control
      description: Automatically adjust fan speed based on temperature deviation
      default: true
      selector:
        boolean:
    
    humidity_comfort_enable:
      name: Humidity Comfort Correction
      description: Apply humidity-based comfort corrections
      default: true
      selector:
        boolean:
    
    comfort_precision_mode:
      name: Precision Comfort Mode
      description: Use high-precision calculations matching CBE tool accuracy
      default: false
      selector:
        boolean:

variables:
  climate_entity_id: !input climate_entity
  indoor_sensor_id: !input indoor_temp_sensor
  outdoor_sensor_id: !input outdoor_temp_sensor
  occupancy_sensor_id: !input occupancy_sensor
  mean_radiant_sensor_id: !input mean_radiant_temp_sensor
  indoor_humidity_sensor_id: !input indoor_humidity_sensor
  outdoor_humidity_sensor_id: !input outdoor_humidity_sensor
  min_comfort_temp_val: !input min_comfort_temp
  max_comfort_temp_val: !input max_comfort_temp
  comfort_category_val: !input comfort_category
  energy_save_mode_val: !input energy_save_mode
  natural_ventilation_enable_val: !input natural_ventilation_enable
  natural_ventilation_threshold_val: !input natural_ventilation_threshold
  setback_temperature_offset_val: !input setback_temperature_offset
  use_operative_temperature_val: !input use_operative_temperature
  air_velocity_val: !input air_velocity
  adaptive_air_velocity_val: !input adaptive_air_velocity
  humidity_comfort_enable_val: !input humidity_comfort_enable
  comfort_precision_mode_val: !input comfort_precision_mode
  
  comfort_tolerance: >
    {% if comfort_category_val == "I" %}
      2.0
    {% elif comfort_category_val == "II" %}
      3.0
    {% else %}
      4.0
    {% endif %}
  
  outdoor_temp: >
    {% if outdoor_sensor_id.startswith('weather.') %}
      {{ state_attr(outdoor_sensor_id, 'temperature') | float(20) }}
    {% else %}
      {{ states(outdoor_sensor_id) | float(20) }}
    {% endif %}
  indoor_air_temp: "{{ states(indoor_sensor_id) | float(20) }}"
  
  # Mean radiant temperature (optional)
  mean_radiant_temp: >
    {% if mean_radiant_sensor_id and mean_radiant_sensor_id != "" %}
      {{ states(mean_radiant_sensor_id) | float(indoor_air_temp) }}
    {% else %}
      {{ indoor_air_temp }}
    {% endif %}
  
  # Operative temperature calculation
  operative_temp: >
    {% if use_operative_temperature_val and mean_radiant_sensor_id and mean_radiant_sensor_id != "" %}
      {{ ((indoor_air_temp + mean_radiant_temp) / 2) | round(1) }}
    {% else %}
      {{ indoor_air_temp }}
    {% endif %}
  
  # Use operative temperature or air temperature
  indoor_temp: "{{ operative_temp }}"
  
  # Humidity readings
  indoor_humidity: >
    {% if indoor_humidity_sensor_id and indoor_humidity_sensor_id != "" %}
      {{ states(indoor_humidity_sensor_id) | float(50) }}
    {% else %}
      50
    {% endif %}
  
  outdoor_humidity: >
    {% if outdoor_humidity_sensor_id and outdoor_humidity_sensor_id != "" %}
      {% if outdoor_humidity_sensor_id.startswith('weather.') %}
        {{ state_attr(outdoor_humidity_sensor_id, 'humidity') | float(50) }}
      {% else %}
        {{ states(outdoor_humidity_sensor_id) | float(50) }}
      {% endif %}
    {% else %}
      50
    {% endif %}
  
  # Air velocity comfort correction (cooling effect) - Only above 25°C operative temp
  air_velocity_offset: >
    {% if operative_temp > 25 and air_velocity_val > 0.3 %}
      {% if air_velocity_val >= 1.2 %}
        -2.2
      {% elif air_velocity_val >= 0.9 %}
        -1.8
      {% elif air_velocity_val >= 0.6 %}
        -1.2
      {% else %}
        {{ -1.2 * ((air_velocity_val - 0.3) / 0.3) | round(1) }}
      {% endif %}
    {% else %}
      0
    {% endif %}
  
  # Humidity comfort correction
  humidity_offset: >
    {% if humidity_comfort_enable_val and indoor_humidity > 60 %}
      {{ 0.3 * ((indoor_humidity - 60) / 10) | round(1) }}
    {% elif humidity_comfort_enable_val and indoor_humidity < 30 %}
      {{ -0.2 * ((30 - indoor_humidity) / 10) | round(1) }}
    {% else %}
      0
    {% endif %}
  
  # Enhanced adaptive comfort temperature with corrections
  base_adaptive_comfort_temp: >
    {{ (18.9 + 0.255 * outdoor_temp) | round(1) }}
  
  # ASHRAE 55 outdoor temperature validation (10-33.5°C range)
  outdoor_temp_valid: >
    {{ outdoor_temp >= 10 and outdoor_temp <= 33.5 }}
  
  adaptive_comfort_temp: >
    {% if outdoor_temp_valid %}
      {% if comfort_precision_mode_val %}
        {{ (base_adaptive_comfort_temp + air_velocity_offset + humidity_offset) | round(1) }}
      {% else %}
        {{ base_adaptive_comfort_temp | round(1) }}
      {% endif %}
    {% else %}
      {{ 22.0 }}
    {% endif %}
  
  comfort_temp_min: >
    {{ [adaptive_comfort_temp - comfort_tolerance, min_comfort_temp_val] | max | round(1) }}
  
  comfort_temp_max: >
    {{ [adaptive_comfort_temp + comfort_tolerance, max_comfort_temp_val] | min | round(1) }}
  
  is_occupied: >
    {% if occupancy_sensor_id and occupancy_sensor_id != "" %}
      {{ is_state(occupancy_sensor_id, 'on') }}
    {% else %}
      true
    {% endif %}
  
  # Enhanced natural ventilation with humidity consideration
  natural_ventilation_available: >
    {% if natural_ventilation_enable_val %}
      {% set temp_suitable = (outdoor_temp >= (indoor_temp - natural_ventilation_threshold_val)) and 
                             (outdoor_temp <= (indoor_temp + natural_ventilation_threshold_val)) and
                             (outdoor_temp >= comfort_temp_min) and 
                             (outdoor_temp <= comfort_temp_max) %}
      {% set humidity_suitable = true %}
      {% if outdoor_humidity_sensor_id and outdoor_humidity_sensor_id != "" %}
        {% set humidity_suitable = (outdoor_humidity <= (indoor_humidity + 10)) %}
      {% endif %}
      {{ temp_suitable and humidity_suitable }}
    {% else %}
      false
    {% endif %}
  
  # Adaptive fan speed calculation
  optimal_fan_speed: >
    {% if adaptive_air_velocity_val and indoor_temp > comfort_temp_max %}
      {% set temp_deviation = indoor_temp - comfort_temp_max %}
      {% if temp_deviation > 3 %}
        high
      {% elif temp_deviation > 1.5 %}
        medium
      {% elif temp_deviation > 0.5 %}
        low
      {% else %}
        auto
      {% endif %}
    {% else %}
      auto
    {% endif %}
  
  target_temp: >
    {% if not is_occupied and energy_save_mode_val %}
      {% if indoor_temp > comfort_temp_max %}
        {{ comfort_temp_max | round(1) }}
      {% elif indoor_temp < comfort_temp_min %}
        {{ max(comfort_temp_min - setback_temperature_offset_val, min_comfort_temp_val) | round(1) }}
      {% else %}
        {{ adaptive_comfort_temp | round(1) }}
      {% endif %}
    {% else %}
      {% if indoor_temp < comfort_temp_min %}
        {{ comfort_temp_min | round(1) }}
      {% elif indoor_temp > comfort_temp_max %}
        {{ comfort_temp_max | round(1) }}
      {% else %}
        {{ adaptive_comfort_temp | round(1) }}
      {% endif %}
    {% endif %}
  
  # ASHRAE 55 compliance notes
  compliance_notes: >
    {% set notes = [] %}
    {% if outdoor_temp < 10 or outdoor_temp > 33.5 %}
      {% set notes = notes + ["Outdoor temp outside ASHRAE 55 range (10-33.5°C): " + outdoor_temp|string + "°C"] %}
    {% endif %}
    {% if operative_temp <= 25 and air_velocity_val > 0.3 %}
      {% set notes = notes + ["Air velocity cooling only applies above 25°C operative temp"] %}
    {% endif %}
    {% if notes|length > 0 %}
      {{ notes | join("; ") }}
    {% else %}
      "Compliant"
    {% endif %}

trigger:
  - platform: time_pattern
    minutes: 0
  - platform: time_pattern
    minutes: 10
  - platform: time_pattern
    minutes: 20
  - platform: time_pattern
    minutes: 30
  - platform: time_pattern
    minutes: 40
  - platform: time_pattern
    minutes: 50
  
  - platform: state
    entity_id: !input indoor_temp_sensor
  
  - platform: state
    entity_id: !input outdoor_temp_sensor
  
  - platform: state
    entity_id: !input occupancy_sensor

condition:
  - condition: template
    value_template: >
      {{ states(climate_entity_id) not in ['unavailable', 'unknown'] and
         states(indoor_sensor_id) not in ['unavailable', 'unknown'] and
         states(outdoor_sensor_id) not in ['unavailable', 'unknown'] }}

action:
  - choose:
      # Natural ventilation mode - turn off HVAC
      - conditions:
          - condition: template
            value_template: "{{ natural_ventilation_available and is_occupied }}"
        sequence:
          - service: climate.turn_off
            target:
              entity_id: !input climate_entity
          - service: logbook.log
            data:
              name: "ASHRAE 55 Adaptive Climate"
              message: >
                Natural ventilation active. HVAC turned off.
                Outdoor: {{ outdoor_temp }}°C, Indoor: {{ indoor_temp }}°C,
                Comfort zone: {{ comfort_temp_min }}-{{ comfort_temp_max }}°C
      
      # Normal climate control
      - conditions:
          - condition: template
            value_template: "{{ not natural_ventilation_available }}"
        sequence:
          - choose:
              # Heating needed
              - conditions:
                  - condition: template
                    value_template: "{{ indoor_temp < comfort_temp_min }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input climate_entity
                    data:
                      hvac_mode: heat
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate_entity
                    data:
                      temperature: "{{ target_temp }}"
                  # Set fan speed for heating
                  - condition: template
                    value_template: "{{ adaptive_air_velocity_val }}"
                  - service: climate.set_fan_mode
                    target:
                      entity_id: !input climate_entity
                    data:
                      fan_mode: "low"
              
              # Cooling needed
              - conditions:
                  - condition: template
                    value_template: "{{ indoor_temp > comfort_temp_max }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input climate_entity
                    data:
                      hvac_mode: cool
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate_entity
                    data:
                      temperature: "{{ target_temp }}"
                  # Set adaptive fan speed for cooling
                  - condition: template
                    value_template: "{{ adaptive_air_velocity_val }}"
                  - service: climate.set_fan_mode
                    target:
                      entity_id: !input climate_entity
                    data:
                      fan_mode: "{{ optimal_fan_speed }}"
              
              # Within comfort zone - maintain current mode but adjust temperature
              - conditions:
                  - condition: template
                    value_template: >
                      {{ indoor_temp >= comfort_temp_min and indoor_temp <= comfort_temp_max }}
                sequence:
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate_entity
                    data:
                      temperature: "{{ target_temp }}"
                  # Set optimal fan speed
                  - condition: template
                    value_template: "{{ adaptive_air_velocity_val }}"
                  - service: climate.set_fan_mode
                    target:
                      entity_id: !input climate_entity
                    data:
                      fan_mode: "auto"
          
          - service: logbook.log
            data:
              name: "ASHRAE 55 Adaptive Climate"
              message: >
                Climate adjusted. Target: {{ target_temp }}°C,
                Indoor: {{ indoor_temp }}°C (Air: {{ indoor_air_temp }}°C{% if use_operative_temperature_val %}, Radiant: {{ mean_radiant_temp }}°C{% endif %}),
                Outdoor: {{ outdoor_temp }}°C, Humidity: {{ indoor_humidity }}%,
                Comfort zone: {{ comfort_temp_min }}-{{ comfort_temp_max }}°C,
                Occupancy: {{ 'Occupied' if is_occupied else 'Unoccupied' }},
                Category: {{ comfort_category_val }} (±{{ comfort_tolerance }}°C),
                {% if comfort_precision_mode_val %}Air velocity offset: {{ air_velocity_offset }}°C, Humidity offset: {{ humidity_offset }}°C,{% endif %}
                {% if adaptive_air_velocity_val %}Fan speed: {{ optimal_fan_speed }},{% endif %}
                Compliance: {{ compliance_notes }}

mode: single
max_exceeded: silent
